server:
  port: 8081

spring:
  application:
    name: lagou-service-resume

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.133.60:3306/lagou?characterEncoding=UTF-8
    username: root
    password: root


  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免驼峰命名转化为下划线

  cloud:
    config:
      name: lagou-service-resume # 应用名称，拉取那个配置文件
      profile: dev # 环境
      label: master # 分支
      uri: http://localhost:8899 # 配置中心地址

config:
  center:
    name: lagou-service-config-dev-11111111111111111111111

management:
  endpoints:
    web:
      exposure:
        include: "*"
